# Generated by Django 2.2.8 on 2020-02-13 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_address_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='availabily',
            field=models.CharField(choices=[('A', 'Available'), ('0', 'Ongoing'), ('H', 'Henceforth')], max_length=1),
        ),
    ]
